# Generated by Django 5.1.6 on 2026-03-09 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("route", "0003_route_type_extension_slot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="航点序号")),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=12, verbose_name="纬度")),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=12, verbose_name="经度")),
                ("altitude", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="飞行高度（米）")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waypoints",
                        to="route.route",
                        verbose_name="所属航线",
                    ),
                ),
            ],
            options={
                "db_table": "waypoints",
                "ordering": ["route_id", "sequence", "id"],
                "permissions": [("view_waypoint", "可查看航点"), ("manage_waypoint", "可管理航点")],
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="waypoint",
            constraint=models.UniqueConstraint(fields=("route", "sequence"), name="waypoints_route_seq_unique"),
        ),
    ]
