# Generated by Django 5.1.6 on 2026-03-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='业务编码')),
                ('name', models.CharField(max_length=128, verbose_name='无人机名称')),
                ('model', models.CharField(max_length=128, verbose_name='型号')),
                ('serial_no', models.CharField(max_length=128, unique=True, verbose_name='出厂序列号')),
                ('status', models.CharField(choices=[('ENABLED', '启用'), ('DISABLED', '停用'), ('MAINTENANCE', '维护中'), ('RETIRED', '已退役')], default='DISABLED', max_length=16, verbose_name='状态')),
                ('org_id', models.BigIntegerField(blank=True, null=True, verbose_name='组织 ID')),
                ('created_by_staff_id', models.BigIntegerField(blank=True, null=True, verbose_name='创建人 Staff ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'drones',
                'ordering': ['-id'],
                'permissions': [('view_drone', '可查看无人机'), ('manage_drone', '可新增与编辑无人机'), ('change_drone_status', '可变更无人机状态')],
                'default_permissions': (),
            },
        ),
    ]
