# Generated by Django 5.1.6 on 2026-03-12 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0004_add_tenant_id_to_business_tables"),
        ("drone", "0002_move_drone_assignment_to_separate_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="drone",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drones",
                to="access.tenant",
                verbose_name="租户",
            ),
        ),
    ]
