# Generated by Django 5.1.6 on 2026-03-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0009_purge_legacy_business_rows_before_tenant_hardening"),
        ("drone", "0004_alter_drone_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drone",
            name="code",
            field=models.CharField(max_length=64, verbose_name="业务编码"),
        ),
        migrations.AlterField(
            model_name="drone",
            name="serial_no",
            field=models.CharField(max_length=128, verbose_name="出厂序列号"),
        ),
        migrations.AddConstraint(
            model_name="drone",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_drone_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="drone",
            constraint=models.UniqueConstraint(
                fields=("tenant", "serial_no"), name="uniq_drone_tenant_serial_no"
            ),
        ),
    ]
