# Generated by Django 5.1.6 on 2026-04-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0012_authsession"),
        ("drone", "0007_refactor_claimed_drone_schema"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="drone",
            constraint=models.UniqueConstraint(
                fields=("device_sn",), name="uniq_drone_device_sn_global"
            ),
        ),
    ]
