# Generated by Django 5.1.6 on 2026-05-27 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0012_authsession"),
        ("dji_bff", "0006_djicloudplatform_and_more"),
        ("drone", "0010_drone_claim_status_and_dji_online"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="drone",
            name="uniq_drone_tenant_device_sn",
        ),
        migrations.RemoveConstraint(
            model_name="drone",
            name="uniq_drone_device_sn_global",
        ),
        migrations.AddField(
            model_name="drone",
            name="dji_platform",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drones",
                to="dji_bff.djicloudplatform",
                verbose_name="DJI 平台",
            ),
        ),
        migrations.AddConstraint(
            model_name="drone",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("dji_platform__isnull", False),
                    models.Q(("status", "RELEASED"), _negated=True),
                ),
                fields=("tenant", "dji_platform", "device_sn"),
                name="uniq_drone_tenant_platform_device_sn",
            ),
        ),
        migrations.AddConstraint(
            model_name="drone",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("dji_platform__isnull", True),
                    models.Q(("status", "RELEASED"), _negated=True),
                ),
                fields=("tenant", "device_sn"),
                name="uniq_drone_tenant_device_sn_legacy",
            ),
        ),
    ]
