# Generated by Django 5.1.6 on 2026-05-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0012_authsession"),
        ("dji_bff", "0006_djicloudplatform_and_more"),
        ("drone", "0011_remove_drone_uniq_drone_tenant_device_sn_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="drone",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("dji_platform__isnull", True),
                    models.Q(("status", "RELEASED"), _negated=True),
                ),
                fields=("device_sn",),
                name="uniq_drone_device_sn_global_legacy",
            ),
        ),
    ]
