# Generated by Django 5.1.6 on 2026-05-31 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam_v2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('level', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'disabled'), (1, 'active')], default=1)),
                ('remark', models.TextField(blank=True, default='')),
                ('account_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_profile', to='iam_v2.v2accountprofile')),
            ],
            options={
                'db_table': 'v2_pilot_profiles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PilotQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qualification_type', models.CharField(max_length=128)),
                ('certificate_no', models.CharField(blank=True, default='', max_length=128)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'disabled'), (1, 'active')], default=1)),
                ('remark', models.TextField(blank=True, default='')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='workforce_v2.pilotprofile')),
            ],
            options={
                'db_table': 'v2_pilot_qualifications',
                'ordering': ['-expires_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('pilot', 'qualification_type', 'certificate_no'), name='uniq_v2_pilot_qualification')],
            },
        ),
    ]
