# Generated by Django 5.1.6 on 2026-05-31 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam_v2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DockResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_sn', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('online_status', models.BooleanField(default=False)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=128)),
                ('firmware_status', models.CharField(blank=True, default='', max_length=64)),
                ('last_payload', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v2_dock_resources',
                'ordering': ['device_sn'],
            },
        ),
        migrations.CreateModel(
            name='DroneResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_sn', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('online_status', models.BooleanField(default=False)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=128)),
                ('firmware_status', models.CharField(blank=True, default='', max_length=64)),
                ('last_payload', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v2_drone_resources',
                'ordering': ['device_sn'],
            },
        ),
        migrations.CreateModel(
            name='DjiConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('base_url', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('login_flag', models.IntegerField(default=1)),
                ('extra_params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ACTIVE', '启用'), ('DISABLED', '停用'), ('ERROR', '异常')], default='ACTIVE', max_length=16)),
                ('workspace_id', models.CharField(blank=True, default='', max_length=128)),
                ('dji_user_id', models.CharField(blank=True, default='', max_length=128)),
                ('dji_username', models.CharField(blank=True, default='', max_length=128)),
                ('dji_user_type', models.CharField(blank=True, default='', max_length=64)),
                ('access_token', models.CharField(blank=True, default='', max_length=512)),
                ('mqtt_username', models.CharField(blank=True, default='', max_length=128)),
                ('mqtt_password', models.CharField(blank=True, default='', max_length=256)),
                ('mqtt_addr', models.CharField(blank=True, default='', max_length=256)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_v2_dji_connections', to=settings.AUTH_USER_MODEL)),
                ('owner_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dji_connections', to='iam_v2.department')),
            ],
            options={
                'db_table': 'v2_dji_connections',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('drone', '无人机'), ('dock', '机场')], max_length=16)),
                ('resource_object_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', '已绑定'), ('UNBOUND', '已解绑')], default='ACTIVE', max_length=16)),
                ('bound_at', models.DateTimeField(blank=True, null=True)),
                ('unbound_at', models.DateTimeField(blank=True, null=True)),
                ('bound_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_v2_resources', to=settings.AUTH_USER_MODEL)),
                ('dji_connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_bindings', to='resource_v2.djiconnection')),
                ('owner_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_bindings', to='iam_v2.department')),
                ('unbound_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unbound_v2_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'v2_resource_bindings',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceBindingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('bind', '绑定'), ('unbind', '解绑')], max_length=16)),
                ('resource_type', models.CharField(choices=[('drone', '无人机'), ('dock', '机场')], max_length=16)),
                ('resource_object_id', models.BigIntegerField()),
                ('resource_identifier', models.CharField(max_length=128)),
                ('dji_connection_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_binding_histories', to='iam_v2.department')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v2_binding_histories', to=settings.AUTH_USER_MODEL)),
                ('new_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_binding_histories', to='iam_v2.department')),
                ('previous_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_binding_histories', to='iam_v2.department')),
            ],
            options={
                'db_table': 'v2_resource_binding_histories',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceSharePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('drone', '无人机'), ('dock', '机场')], max_length=16)),
                ('resource_object_id', models.BigIntegerField()),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('share_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_permissions', to='iam_v2.resourcesharegroup')),
            ],
            options={
                'db_table': 'v2_resource_share_permissions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='V2AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128)),
                ('resource_type', models.CharField(blank=True, max_length=16)),
                ('resource_object_id', models.CharField(blank=True, max_length=64)),
                ('target_type', models.CharField(max_length=128)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_v2_audit_logs', to='iam_v2.department')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v2_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('resource_owner_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_owner_v2_audit_logs', to='iam_v2.department')),
            ],
            options={
                'db_table': 'v2_audit_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='djiconnection',
            constraint=models.UniqueConstraint(fields=('owner_department', 'name'), name='uniq_v2_dji_connection_owner_name'),
        ),
        migrations.AddIndex(
            model_name='resourcebinding',
            index=models.Index(fields=['resource_type', 'resource_object_id', 'status'], name='idx_v2_binding_resource'),
        ),
        migrations.AddIndex(
            model_name='resourcebinding',
            index=models.Index(fields=['owner_department', 'status'], name='idx_v2_binding_owner_status'),
        ),
        migrations.AddConstraint(
            model_name='resourcebinding',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('resource_type', 'resource_object_id'), name='uniq_v2_active_resource_binding'),
        ),
        migrations.AddConstraint(
            model_name='resourcesharepermission',
            constraint=models.UniqueConstraint(fields=('share_group', 'resource_type', 'resource_object_id'), name='uniq_v2_share_group_resource'),
        ),
        migrations.AddIndex(
            model_name='v2auditlog',
            index=models.Index(fields=['actor_department', 'created_at'], name='idx_v2_audit_actor_dept'),
        ),
        migrations.AddIndex(
            model_name='v2auditlog',
            index=models.Index(fields=['resource_type', 'resource_object_id'], name='idx_v2_audit_resource'),
        ),
    ]
