# Generated by Django 5.1.6 on 2026-05-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_v2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayloadResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload_sn', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('payload_type', models.CharField(blank=True, default='', max_length=64)),
                ('online_status', models.BooleanField(default=False)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=128)),
                ('firmware_status', models.CharField(blank=True, default='', max_length=64)),
                ('last_payload', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v2_payload_resources',
                'ordering': ['payload_sn'],
            },
        ),
        migrations.AlterField(
            model_name='resourcebinding',
            name='resource_type',
            field=models.CharField(choices=[('drone', '无人机'), ('dock', '机场'), ('payload', '负载')], max_length=16),
        ),
        migrations.AlterField(
            model_name='resourcebindinghistory',
            name='resource_type',
            field=models.CharField(choices=[('drone', '无人机'), ('dock', '机场'), ('payload', '负载')], max_length=16),
        ),
        migrations.AlterField(
            model_name='resourcesharepermission',
            name='resource_type',
            field=models.CharField(choices=[('drone', '无人机'), ('dock', '机场'), ('payload', '负载')], max_length=16),
        ),
    ]
