# Generated by Django 5.1.6 on 2026-06-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_v2", "0003_gatewayresource_resource_type_gateway"),
    ]

    operations = [
        migrations.CreateModel(
            name="DroneTelemetrySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=12, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=12, null=True
                    ),
                ),
                (
                    "altitude",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "speed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "heading",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("battery_percent", models.PositiveIntegerField(blank=True, null=True)),
                ("reported_at", models.DateTimeField()),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "dji_connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drone_telemetry_snapshots",
                        to="resource_v2.djiconnection",
                    ),
                ),
                (
                    "drone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="latest_telemetry",
                        to="resource_v2.droneresource",
                    ),
                ),
            ],
            options={
                "db_table": "v2_drone_telemetry_snapshots",
                "ordering": ["-reported_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MqttConnectionHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISCONNECTED", "未连接"),
                            ("CONNECTING", "连接中"),
                            ("SUBSCRIBED", "已订阅"),
                            ("MESSAGE_RECEIVED", "已收包"),
                            ("ERROR", "异常"),
                        ],
                        default="DISCONNECTED",
                        max_length=32,
                    ),
                ),
                ("worker_id", models.CharField(blank=True, default="", max_length=128)),
                ("mqtt_addr", models.CharField(blank=True, default="", max_length=256)),
                ("subscribed_topics", models.JSONField(blank=True, default=list)),
                ("last_connected_at", models.DateTimeField(blank=True, null=True)),
                ("last_subscribed_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("message_count", models.PositiveBigIntegerField(default=0)),
                (
                    "dji_connection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mqtt_health",
                        to="resource_v2.djiconnection",
                    ),
                ),
            ],
            options={
                "db_table": "v2_mqtt_connection_health",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MqttLatestMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("topic", models.CharField(max_length=512)),
                ("topic_kind", models.CharField(blank=True, default="", max_length=64)),
                ("device_sn", models.CharField(blank=True, default="", max_length=128)),
                ("received_at", models.DateTimeField()),
                ("sequence", models.PositiveBigIntegerField(default=0)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "dji_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mqtt_latest_messages",
                        to="resource_v2.djiconnection",
                    ),
                ),
            ],
            options={
                "db_table": "v2_mqtt_latest_messages",
                "ordering": ["-received_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["dji_connection", "topic_kind", "device_sn"],
                        name="idx_v2_mqtt_latest_filter",
                    ),
                    models.Index(
                        fields=["device_sn", "received_at"],
                        name="idx_v2_mqtt_latest_device_time",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dji_connection", "topic", "device_sn"),
                        name="uniq_v2_mqtt_latest_connection_topic_device",
                    )
                ],
            },
        ),
    ]
