# Generated by refactor: audit_v2 owns V2AuditLog state; v2_audit_logs table stays put.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit_v2", "0001_initial"),
        ("resource_v2", "0004_dronetelemetrysnapshot_mqttconnectionhealth_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="V2AuditLog"),
            ],
        ),
    ]
