# Generated by Django 5.1.6 on 2026-05-31 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0012_authsession'),
        ('iam_v2', '0001_initial'),
        ('resource_v2', '0002_payloadresource_alter_resourcebinding_resource_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=128)),
                ('level', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'disabled'), (1, 'active')], default=1)),
                ('remark', models.TextField(blank=True, default='')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_profile', to='iam_v2.v2accountprofile')),
            ],
            options={
                'db_table': 'v2_inspection_pilot_profiles',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status', 'deleted_at'], name='idx_v2_pilot_profile_status')],
            },
        ),
        migrations.CreateModel(
            name='PilotQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qualification_type', models.CharField(max_length=128)),
                ('certificate_no', models.CharField(max_length=128)),
                ('issued_at', models.DateField()),
                ('expires_at', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'disabled'), (1, 'active')])),
                ('remark', models.TextField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='inspection_v2.pilotprofile')),
            ],
            options={
                'db_table': 'v2_inspection_pilot_qualifications',
                'ordering': ['-expires_at', '-id'],
                'indexes': [models.Index(fields=['pilot', 'deleted_at'], name='idx_v2_pilot_qual_pilot')],
                'constraints': [models.UniqueConstraint(fields=('pilot', 'qualification_type', 'certificate_no'), name='uniq_v2_inspection_pilot_qualification')],
            },
        ),
        migrations.CreateModel(
            name='MissionResourceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('drone', '无人机'), ('dock', '机场'), ('payload', '负载')], max_length=16)),
                ('resource_object_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'v2_mission_resource_assignments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('altitude', models.DecimalField(decimal_places=2, max_digits=10)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('hover_seconds', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'v2_waypoints',
                'ordering': ['route_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='WaypointRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'disabled'), (1, 'active')], default=1)),
                ('default_altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remark', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'v2_waypoint_routes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FlightSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('RUNNING', '执行中'), ('COMPLETED', '已完成'), ('CANCELED', '已取消'), ('FAILED', '失败')], default='RUNNING', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('dock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='v2_flight_sessions', to='resource_v2.dockresource')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='v2_flight_sessions', to='resource_v2.droneresource')),
                ('ended_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_v2_flight_sessions', to=settings.AUTH_USER_MODEL)),
                ('payload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='v2_flight_sessions', to='resource_v2.payloadresource')),
                ('started_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_v2_flight_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'v2_flight_sessions',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FlightTelemetrySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('battery_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('reported_at', models.DateTimeField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_snapshot', to='inspection_v2.flightsession')),
            ],
            options={
                'db_table': 'v2_flight_telemetry_snapshots',
            },
        ),
        migrations.CreateModel(
            name='InspectionFlightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight_no', models.CharField(max_length=64, unique=True)),
                ('mission_name', models.CharField(max_length=128)),
                ('route_name', models.CharField(max_length=128)),
                ('drone_device_sn', models.CharField(max_length=128)),
                ('drone_name', models.CharField(blank=True, default='', max_length=128)),
                ('pilot_name', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('flight_duration', models.PositiveIntegerField(default=0)),
                ('photo_count', models.PositiveIntegerField(default=0)),
                ('video_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('COMPLETED', '已完成'), ('CANCELED', '已取消'), ('FAILED', '失败')], default='COMPLETED', max_length=16)),
                ('remark', models.TextField(blank=True, default='')),
                ('abnormal_reason', models.TextField(blank=True, default='')),
                ('creator_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_v2_flight_records', to='iam_v2.department')),
                ('primary_resource_owner_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_resource_v2_flight_records', to='iam_v2.department')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='flight_record', to='inspection_v2.flightsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v2_flight_records', to='access.tenant')),
            ],
            options={
                'db_table': 'v2_inspection_flight_records',
                'ordering': ['-end_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CloudMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_sn', models.CharField(max_length=128)),
                ('cloud_file_id', models.CharField(max_length=256)),
                ('media_type', models.CharField(choices=[('PHOTO', '照片'), ('VIDEO', '视频'), ('OTHER', '其他')], default='OTHER', max_length=16)),
                ('file_name', models.CharField(blank=True, default='', max_length=256)),
                ('thumbnail_url', models.CharField(blank=True, default='', max_length=1000)),
                ('preview_url', models.CharField(blank=True, default='', max_length=1000)),
                ('download_url', models.CharField(blank=True, default='', max_length=1000)),
                ('playback_url', models.CharField(blank=True, default='', max_length=1000)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v2_cloud_media_files', to='access.tenant')),
                ('flight_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='inspection_v2.inspectionflightrecord')),
            ],
            options={
                'db_table': 'v2_cloud_media_files',
                'ordering': ['-captured_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_snapshot', models.JSONField(default=dict)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('PENDING', '待执行'), ('RUNNING', '执行中'), ('COMPLETED', '已完成'), ('CANCELED', '已取消'), ('FAILED', '失败')], default='PENDING', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('remark', models.TextField(blank=True, default='')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_v2_inspection_missions', to=settings.AUTH_USER_MODEL)),
                ('creator_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_v2_missions', to='iam_v2.department')),
                ('dock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='v2_missions', to='resource_v2.dockresource')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='v2_missions', to='resource_v2.droneresource')),
                ('payload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='v2_missions', to='resource_v2.payloadresource')),
            ],
            options={
                'db_table': 'v2_inspection_missions',
                'ordering': ['-id'],
            },
        ),
    ]
