# Generated by Django 5.1.6 on 2026-05-31 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0012_authsession'),
        ('iam_v2', '0001_initial'),
        ('inspection_v2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionmission',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='v2_missions', to='inspection_v2.pilotprofile'),
        ),
        migrations.AddField(
            model_name='inspectionmission',
            name='primary_resource_owner_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_resource_v2_missions', to='iam_v2.department'),
        ),
        migrations.AddField(
            model_name='inspectionmission',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v2_inspection_missions', to='access.tenant'),
        ),
        migrations.AddField(
            model_name='inspectionflightrecord',
            name='mission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='flight_record', to='inspection_v2.inspectionmission'),
        ),
        migrations.AddField(
            model_name='flightsession',
            name='mission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flight_session', to='inspection_v2.inspectionmission'),
        ),
        migrations.AddField(
            model_name='cloudmediafile',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='inspection_v2.inspectionmission'),
        ),
        migrations.AddField(
            model_name='missionresourceassignment',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='inspection_v2.inspectionmission'),
        ),
        migrations.AddField(
            model_name='missionresourceassignment',
            name='owner_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='v2_mission_resource_assignments', to='iam_v2.department'),
        ),
        migrations.AddField(
            model_name='waypointroute',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_v2_waypoint_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waypointroute',
            name='owner_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='v2_waypoint_routes', to='iam_v2.department'),
        ),
        migrations.AddField(
            model_name='waypointroute',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v2_waypoint_routes', to='access.tenant'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='inspection_v2.waypointroute'),
        ),
        migrations.AddField(
            model_name='inspectionmission',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='inspection_v2.waypointroute'),
        ),
        migrations.AddIndex(
            model_name='inspectionflightrecord',
            index=models.Index(fields=['tenant', 'status'], name='idx_v2_record_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='inspectionflightrecord',
            index=models.Index(fields=['drone_device_sn', 'start_time', 'end_time'], name='idx_v2_record_drone_time'),
        ),
        migrations.AddIndex(
            model_name='flightsession',
            index=models.Index(fields=['status', 'drone'], name='idx_v2_session_status_drone'),
        ),
        migrations.AddIndex(
            model_name='cloudmediafile',
            index=models.Index(fields=['device_sn', 'captured_at'], name='idx_v2_media_device_time'),
        ),
        migrations.AddConstraint(
            model_name='cloudmediafile',
            constraint=models.UniqueConstraint(fields=('tenant', 'cloud_file_id'), name='uniq_v2_cloud_media_file'),
        ),
        migrations.AddIndex(
            model_name='missionresourceassignment',
            index=models.Index(fields=['resource_type', 'resource_object_id'], name='idx_v2_mission_resource'),
        ),
        migrations.AddIndex(
            model_name='missionresourceassignment',
            index=models.Index(fields=['owner_department'], name='idx_v2_mission_resource_owner'),
        ),
        migrations.AddConstraint(
            model_name='missionresourceassignment',
            constraint=models.UniqueConstraint(fields=('mission', 'resource_type', 'resource_object_id'), name='uniq_v2_mission_resource_assignment'),
        ),
        migrations.AddConstraint(
            model_name='waypointroute',
            constraint=models.UniqueConstraint(fields=('owner_department', 'name'), name='uniq_v2_route_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='waypoint',
            constraint=models.UniqueConstraint(fields=('route', 'sequence'), name='uniq_v2_route_waypoint_sequence'),
        ),
        migrations.AddIndex(
            model_name='inspectionmission',
            index=models.Index(fields=['tenant', 'status'], name='idx_v2_mission_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='inspectionmission',
            index=models.Index(fields=['creator_department', 'status'], name='idx_v2_mission_creator_status'),
        ),
        migrations.AddIndex(
            model_name='inspectionmission',
            index=models.Index(fields=['primary_resource_owner_department', 'status'], name='idx_v2_mission_owner_status'),
        ),
    ]
