# Generated by Django 5.1.6 on 2026-05-31 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_v2', '0002_initial'),
        ('resource_v2', '0002_payloadresource_alter_resourcebinding_resource_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='flightsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'RUNNING')), fields=('drone',), name='uniq_v2_running_session_drone'),
        ),
        migrations.AddConstraint(
            model_name='flightsession',
            constraint=models.UniqueConstraint(condition=models.Q(('dock__isnull', False), ('status', 'RUNNING')), fields=('dock',), name='uniq_v2_running_session_dock'),
        ),
        migrations.AddConstraint(
            model_name='flightsession',
            constraint=models.UniqueConstraint(condition=models.Q(('payload__isnull', False), ('status', 'RUNNING')), fields=('payload',), name='uniq_v2_running_session_payload'),
        ),
    ]
