# Generated by Codex on 2026-06-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection_v2", "0003_flightsession_uniq_v2_running_session_drone_and_more"),
        ("resource_v2", "0003_gatewayresource_resource_type_gateway"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WaypointRouteCloudFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("workspace_id", models.CharField(max_length=128)),
                ("dji_file_id", models.CharField(max_length=128)),
                ("download_url", models.CharField(blank=True, default="", max_length=1000)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dji_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="v2_route_cloud_files",
                        to="resource_v2.djiconnection",
                    ),
                ),
                (
                    "route",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloud_file",
                        to="inspection_v2.waypointroute",
                    ),
                ),
                (
                    "uploaded_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_v2_route_cloud_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "v2_waypoint_route_cloud_files",
            },
        ),
        migrations.AddField(
            model_name="inspectionmission",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="v2_missions",
                to="resource_v2.gatewayresource",
            ),
        ),
        migrations.AddField(
            model_name="flightsession",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="v2_flight_sessions",
                to="resource_v2.gatewayresource",
            ),
        ),
        migrations.AddConstraint(
            model_name="waypointroutecloudfile",
            constraint=models.UniqueConstraint(fields=("dji_connection", "dji_file_id"), name="uniq_v2_route_cloud_file_dji"),
        ),
        migrations.AddConstraint(
            model_name="flightsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("executor__isnull", False), ("status", "RUNNING")),
                fields=("executor",),
                name="uniq_v2_running_session_executor",
            ),
        ),
        migrations.CreateModel(
            name="MissionCloudExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("workspace_id", models.CharField(max_length=128)),
                ("dji_job_id", models.CharField(blank=True, default="", max_length=128)),
                ("executor_sn", models.CharField(max_length=128)),
                ("drone_sn", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTING", "启动中"),
                            ("RUNNING", "执行中"),
                            ("COMPLETED", "已完成"),
                            ("CANCELED", "已取消"),
                            ("FAILED", "失败"),
                        ],
                        default="STARTING",
                        max_length=16,
                    ),
                ),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("raw_request", models.JSONField(blank=True, default=dict)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("raw_last_event", models.JSONField(blank=True, default=dict)),
                (
                    "dji_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="v2_mission_cloud_executions",
                        to="resource_v2.djiconnection",
                    ),
                ),
                (
                    "mission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloud_execution",
                        to="inspection_v2.inspectionmission",
                    ),
                ),
                (
                    "route_cloud_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mission_executions",
                        to="inspection_v2.waypointroutecloudfile",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cloud_execution",
                        to="inspection_v2.flightsession",
                    ),
                ),
            ],
            options={
                "db_table": "v2_mission_cloud_executions",
            },
        ),
        migrations.AddConstraint(
            model_name="missioncloudexecution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dji_job_id", ""), _negated=True),
                fields=("dji_connection", "dji_job_id"),
                name="uniq_v2_cloud_execution_job",
            ),
        ),
    ]
