# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection_v2", "0004_route_cloud_file_executor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missionresourceassignment",
            name="resource_type",
            field=models.CharField(
                choices=[("drone", "无人机"), ("dock", "机场"), ("gateway", "执行端/网关"), ("payload", "负载")],
                max_length=16,
            ),
        ),
    ]
