# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection_v2", "0005_alter_missionresourceassignment_resource_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="waypointroutecloudfile",
            name="wayline_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "waypoint"), (1, "mapping2d"), (2, "mapping3d"), (3, "mappingStrip")],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="cloudmediafile",
            name="workspace_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="cloudmediafile",
            name="dji_job_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="cloudmediafile",
            name="object_key",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="cloudmediafile",
            name="fingerprint",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="cloudmediafile",
            name="file_group_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddIndex(
            model_name="cloudmediafile",
            index=models.Index(fields=["workspace_id", "dji_job_id"], name="idx_v2_media_workspace_job"),
        ),
    ]
