# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection_v2", "0006_wayline_type_and_cloud_media_job_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="missioncloudexecution",
            name="live_status",
            field=models.CharField(
                choices=[
                    ("STOPPED", "已停止"),
                    ("STARTING", "启动中"),
                    ("RUNNING", "直播中"),
                    ("STOPPING", "停止中"),
                    ("FAILED", "异常"),
                ],
                default="STOPPED",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="missioncloudexecution",
            name="live_video_id",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="missioncloudexecution",
            name="live_url_type",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="missioncloudexecution",
            name="live_video_quality",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="missioncloudexecution",
            name="live_urls",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="missioncloudexecution",
            name="live_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="missioncloudexecution",
            name="live_stopped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="missioncloudexecution",
            name="live_error_message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
