# Generated by Django 5.1.6 on 2026-06-15 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_v2', '0013_mission_execution_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionFlightRecordMediaSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', '待同步'), ('RUNNING', '同步中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=16)),
                ('next_run_at', models.DateTimeField()),
                ('deadline_at', models.DateTimeField()),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('last_photo_count', models.PositiveIntegerField(default=0)),
                ('last_video_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('flight_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_sync_state', to='inspection_v2.inspectionflightrecord')),
            ],
            options={
                'db_table': 'v2_inspection_flight_record_media_sync_states',
                'indexes': [models.Index(fields=['status', 'next_run_at'], name='idx_v2_media_sync_due')],
            },
        ),
    ]
