# Generated by Django 5.1.6 on 2026-08-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection_v2", "0015_alter_missionresourceassignment_resource_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionmission",
            name="exit_wayline_when_rc_lost",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "继续航线"), (1, "执行失联动作")], default=1
            ),
        ),
        migrations.AddField(
            model_name="inspectionmission",
            name="out_of_control_action",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "返航"), (1, "悬停"), (2, "降落")], default=0
            ),
        ),
        migrations.AddField(
            model_name="inspectionmission",
            name="rth_altitude",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="inspectionmission",
            name="rth_mode",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "最佳高度"), (1, "预设高度")], default=1
            ),
        ),
        migrations.AddField(
            model_name="inspectionmission",
            name="wayline_precision_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "GNSS/GPS"), (1, "RTK")], default=1
            ),
        ),
    ]
