# Generated by Django 5.1.6 on 2026-03-08 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("access", "0001_initial"),
        ("drone", "0002_move_drone_assignment_to_separate_app"),
        ("mission", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flight_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="架次编号"
                    ),
                ),
                (
                    "mission_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="任务名称（冗余）",
                    ),
                ),
                (
                    "route_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="航线名称（冗余）",
                    ),
                ),
                (
                    "airport_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="执行机场名称",
                    ),
                ),
                (
                    "drone_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="无人机名称（冗余）",
                    ),
                ),
                (
                    "pilot_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="飞手姓名（冗余）",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "flight_duration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="飞行时长（秒）"
                    ),
                ),
                (
                    "photo_count",
                    models.PositiveIntegerField(default=0, verbose_name="拍摄照片数量"),
                ),
                (
                    "video_count",
                    models.PositiveIntegerField(default=0, verbose_name="录制视频数量"),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "飞行中"), (1, "已完成"), (2, "异常终止")],
                        default=0,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "drone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flight_records",
                        to="drone.drone",
                        verbose_name="执行无人机",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flight_records",
                        to="mission.mission",
                        verbose_name="所属任务",
                    ),
                ),
                (
                    "pilot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flight_records",
                        to="access.staffprofile",
                        verbose_name="执行飞手",
                    ),
                ),
            ],
            options={
                "db_table": "flight_records",
                "ordering": ["-id"],
                "permissions": [("view_flight_record", "可查看飞行记录")],
                "default_permissions": (),
            },
        ),
    ]
