# Generated by Django 5.1.6 on 2026-03-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flight_record", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flightrecord",
            options={
                "default_permissions": (),
                "ordering": ["-id"],
                "permissions": [
                    ("view_flight_record", "可查看飞行记录"),
                    ("manage_flight_record", "可新增与编辑飞行记录"),
                ],
            },
        ),
    ]
