# Generated by Django 5.1.6 on 2026-03-14 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0009_purge_legacy_business_rows_before_tenant_hardening"),
        ("flight_record", "0003_add_tenant_id_to_business_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightrecord",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flight_records",
                to="access.tenant",
                verbose_name="租户",
            ),
        ),
    ]
