# Generated by Django 5.1.6 on 2026-03-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0009_purge_legacy_business_rows_before_tenant_hardening"),
        ("drone", "0005_alter_drone_code_alter_drone_serial_no_and_more"),
        ("flight_record", "0004_alter_flightrecord_tenant"),
        ("mission", "0003_alter_mission_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightrecord",
            name="flight_no",
            field=models.CharField(max_length=50, verbose_name="架次编号"),
        ),
        migrations.AddConstraint(
            model_name="flightrecord",
            constraint=models.UniqueConstraint(
                fields=("tenant", "flight_no"),
                name="uniq_flight_record_tenant_flight_no",
            ),
        ),
    ]
