# Generated by Django 5.1.6 on 2026-03-15 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0011_user_is_platform_admin"),
        ("flight_record", "0005_alter_flightrecord_flight_no_and_more"),
        ("mission", "0004_alter_mission_pilot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightrecord",
            name="pilot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flight_records",
                to="access.tenantmember",
                verbose_name="执行飞手成员",
            ),
        ),
    ]
