# Generated by Django 5.1.6 on 2026-04-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0012_authsession"),
        ("drone", "0010_drone_claim_status_and_dji_online"),
        ("flight_record", "0006_alter_flightrecord_pilot"),
        ("mission", "0008_mission_execution_window"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightrecord",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="flightrecord",
            name="device_sn",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="设备序列号（冗余）",
            ),
        ),
        migrations.AddField(
            model_name="flightrecord",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
        migrations.AddConstraint(
            model_name="flightrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("mission__isnull", False)),
                fields=("mission",),
                name="uniq_flight_record_mission",
            ),
        ),
    ]
