# Generated by Django 5.1.6 on 2026-05-27 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dji_bff", "0006_djicloudplatform_and_more"),
        (
            "flight_record",
            "0007_flightrecord_deleted_at_flightrecord_device_sn_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="flightrecord",
            name="dji_platform",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flight_records",
                to="dji_bff.djicloudplatform",
                verbose_name="DJI 平台",
            ),
        ),
    ]
