# Generated by Django 5.1.6 on 2026-03-30

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("access", "0012_authsession"),
        ("route", "0005_alter_route_tenant"),
        ("mission", "0004_alter_mission_pilot"),
        ("media_file", "0004_alter_mediafile_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjiWorkspaceConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("workspace_id", models.CharField(max_length=128, unique=True, verbose_name="DJI workspace ID")),
                ("dji_user_id", models.CharField(blank=True, default="", max_length=128, verbose_name="DJI user ID")),
                ("dji_username", models.CharField(blank=True, default="", max_length=128, verbose_name="DJI 用户名")),
                ("dji_user_type", models.CharField(blank=True, default="", max_length=64, verbose_name="DJI 用户类型")),
                ("access_token", models.CharField(blank=True, default="", max_length=512, verbose_name="访问令牌")),
                ("mqtt_username", models.CharField(blank=True, default="", max_length=128, verbose_name="MQTT 用户名")),
                ("mqtt_password", models.CharField(blank=True, default="", max_length=256, verbose_name="MQTT 密码")),
                ("mqtt_addr", models.CharField(blank=True, default="", max_length=256, verbose_name="MQTT 地址")),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="访问令牌过期时间")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "dji_workspace_configs", "ordering": ["-id"]},
        ),
        migrations.CreateModel(
            name="DjiDeviceIndex",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_sn", models.CharField(max_length=128, unique=True, verbose_name="设备序列号")),
                ("last_payload", models.JSONField(blank=True, default=dict, verbose_name="最近一次 DJI 原始载荷")),
                ("last_seen_at", models.DateTimeField(blank=True, null=True, verbose_name="最近见到时间")),
                ("firmware_version", models.CharField(blank=True, default="", max_length=128, verbose_name="固件版本")),
                ("firmware_status", models.CharField(blank=True, default="", max_length=64, verbose_name="固件状态")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "dji_device_indexes", "ordering": ["device_sn"]},
        ),
        migrations.CreateModel(
            name="TenantRouteIndex",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dji_wayline_id", models.CharField(blank=True, default="", max_length=128, verbose_name="DJI 航线 ID")),
                ("is_published", models.BooleanField(default=False, verbose_name="是否已发布")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "route",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="dji_index", to="route.route"),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dji_route_indexes", to="access.tenant"),
                ),
            ],
            options={"db_table": "tenant_route_indexes", "ordering": ["-id"]},
        ),
        migrations.CreateModel(
            name="TenantMissionIndex",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dji_job_id", models.CharField(max_length=128, verbose_name="DJI 任务 ID")),
                ("execution_status", models.CharField(blank=True, default="", max_length=64, verbose_name="执行状态")),
                (
                    "sync_status",
                    models.CharField(
                        choices=[("PENDING", "同步中"), ("SYNCED", "同步成功"), ("ERROR", "同步失败")],
                        default="PENDING",
                        max_length=32,
                        verbose_name="同步状态",
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True, verbose_name="最近同步时间")),
                ("error_msg", models.CharField(blank=True, default="", max_length=255, verbose_name="同步错误")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mission",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="dji_index", to="mission.mission"),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dji_mission_indexes", to="access.tenant"),
                ),
            ],
            options={"db_table": "tenant_mission_indexes", "ordering": ["-id"]},
        ),
        migrations.CreateModel(
            name="TenantMediaIndex",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dji_file_id", models.CharField(max_length=128, verbose_name="DJI 文件 ID")),
                ("device_sn", models.CharField(blank=True, default="", max_length=128, verbose_name="设备序列号")),
                (
                    "sync_status",
                    models.CharField(
                        choices=[("PENDING", "同步中"), ("SYNCED", "同步成功"), ("ERROR", "同步失败")],
                        default="PENDING",
                        max_length=32,
                        verbose_name="同步状态",
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True, verbose_name="最近同步时间")),
                ("error_msg", models.CharField(blank=True, default="", max_length=255, verbose_name="同步错误")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media_file",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="dji_index", to="media_file.mediafile"),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dji_media_indexes",
                        to="mission.mission",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dji_media_indexes", to="access.tenant"),
                ),
            ],
            options={"db_table": "tenant_media_indexes", "ordering": ["-id"]},
        ),
        migrations.AddConstraint(
            model_name="tenantrouteindex",
            constraint=models.UniqueConstraint(
                condition=Q(dji_wayline_id__isnull=False) & ~Q(dji_wayline_id=""),
                fields=("tenant", "dji_wayline_id"),
                name="uniq_tenant_dji_wayline_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantmissionindex",
            constraint=models.UniqueConstraint(fields=("tenant", "dji_job_id"), name="uniq_tenant_dji_job_id"),
        ),
        migrations.AddConstraint(
            model_name="tenantmediaindex",
            constraint=models.UniqueConstraint(fields=("tenant", "dji_file_id"), name="uniq_tenant_dji_file_id"),
        ),
    ]
