# Generated by Django 5.1.6 on 2026-05-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dji_bff", "0003_remove_tenantmissionindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantmediaindex",
            name="workspace_id",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="DJI workspace ID"
            ),
        ),
    ]
