# Generated by Django 5.1.6 on 2026-05-27 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0012_authsession"),
        ("dji_bff", "0005_add_workspace_id_to_tenant_route_index"),
        ("media_file", "0005_mediafile_device_sn_mediafile_mission"),
        ("mission", "0008_mission_execution_window"),
        ("route", "0007_remove_route_xml_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjiCloudPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="平台名称")),
                (
                    "base_url",
                    models.CharField(max_length=500, verbose_name="DJI API Base URL"),
                ),
                (
                    "username",
                    models.CharField(max_length=128, verbose_name="DJI 登录用户名"),
                ),
                (
                    "password",
                    models.CharField(max_length=256, verbose_name="DJI 登录密码"),
                ),
                (
                    "login_flag",
                    models.IntegerField(default=1, verbose_name="DJI 登录 flag"),
                ),
                (
                    "workspace_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="DJI workspace ID",
                    ),
                ),
                (
                    "dji_user_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="DJI user ID",
                    ),
                ),
                (
                    "dji_username",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="DJI 用户名",
                    ),
                ),
                (
                    "dji_user_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="DJI 用户类型",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True, default="", max_length=512, verbose_name="访问令牌"
                    ),
                ),
                (
                    "mqtt_username",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="MQTT 用户名",
                    ),
                ),
                (
                    "mqtt_password",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="MQTT 密码"
                    ),
                ),
                (
                    "mqtt_addr",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="MQTT 地址"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="访问令牌过期时间"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认平台"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "启用"),
                            ("DISABLED", "停用"),
                            ("ERROR", "异常"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                        verbose_name="平台状态",
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近连接检测时间"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dji_cloud_platforms",
                "ordering": ["-id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="tenantmediaindex",
            name="uniq_tenant_dji_file_id",
        ),
        migrations.RemoveConstraint(
            model_name="tenantrouteindex",
            name="uniq_tenant_dji_wayline_id",
        ),
        migrations.AlterField(
            model_name="djideviceindex",
            name="device_sn",
            field=models.CharField(max_length=128, verbose_name="设备序列号"),
        ),
        migrations.AddField(
            model_name="djicloudplatform",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dji_cloud_platforms",
                to="access.tenant",
            ),
        ),
        migrations.AddField(
            model_name="djideviceindex",
            name="dji_platform",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_indexes",
                to="dji_bff.djicloudplatform",
                verbose_name="DJI 平台",
            ),
        ),
        migrations.AddField(
            model_name="tenantmediaindex",
            name="dji_platform",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_indexes",
                to="dji_bff.djicloudplatform",
                verbose_name="DJI 平台",
            ),
        ),
        migrations.AddField(
            model_name="tenantrouteindex",
            name="dji_platform",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_indexes",
                to="dji_bff.djicloudplatform",
                verbose_name="DJI 平台",
            ),
        ),
        migrations.AddConstraint(
            model_name="djideviceindex",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dji_platform__isnull", False)),
                fields=("dji_platform", "device_sn"),
                name="uniq_dji_device_index_platform_sn",
            ),
        ),
        migrations.AddConstraint(
            model_name="djideviceindex",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dji_platform__isnull", True)),
                fields=("device_sn",),
                name="uniq_dji_device_index_legacy_sn",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantmediaindex",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dji_platform__isnull", False)),
                fields=("dji_platform", "dji_file_id"),
                name="uniq_platform_dji_file_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantmediaindex",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dji_platform__isnull", True)),
                fields=("tenant", "dji_file_id"),
                name="uniq_tenant_dji_file_id_legacy",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantrouteindex",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("dji_platform__isnull", False),
                    ("dji_wayline_id__isnull", False),
                    models.Q(("dji_wayline_id", ""), _negated=True),
                ),
                fields=("dji_platform", "dji_wayline_id"),
                name="uniq_platform_dji_wayline_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantrouteindex",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("dji_platform__isnull", True),
                    ("dji_wayline_id__isnull", False),
                    models.Q(("dji_wayline_id", ""), _negated=True),
                ),
                fields=("tenant", "dji_wayline_id"),
                name="uniq_tenant_dji_wayline_id_legacy",
            ),
        ),
        migrations.AddConstraint(
            model_name="djicloudplatform",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uniq_dji_cloud_platform_tenant_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="djicloudplatform",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("tenant",),
                name="uniq_dji_cloud_platform_tenant_default",
            ),
        ),
    ]
