# Generated by Django 5.1.6 on 2026-03-08 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("access", "0001_initial"),
        ("drone", "0002_move_drone_assignment_to_separate_app"),
        ("route", "0003_route_type_extension_slot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="任务名称")),
                (
                    "route_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="航线名称（冗余）",
                    ),
                ),
                (
                    "drone_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="无人机名称（冗余）",
                    ),
                ),
                (
                    "pilot_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="飞手姓名（冗余）",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="计划执行时间"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="任务备注"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "待执行"),
                            (1, "执行中"),
                            (2, "已暂停"),
                            (3, "已完成"),
                            (4, "已取消"),
                            (5, "执行失败"),
                        ],
                        default=0,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="missions",
                        to="drone.drone",
                        verbose_name="无人机",
                    ),
                ),
                (
                    "pilot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="missions",
                        to="access.staffprofile",
                        verbose_name="飞手",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="missions",
                        to="route.route",
                        verbose_name="航线",
                    ),
                ),
            ],
            options={
                "db_table": "missions",
                "ordering": ["-id"],
                "permissions": [
                    ("view_mission", "可查看任务"),
                    ("manage_mission", "可新增与编辑任务"),
                ],
                "default_permissions": (),
            },
        ),
    ]
