# Generated by Django 5.1.6 on 2026-03-15 14:05

import django.db.models.deletion
from django.db import migrations, models


def purge_legacy_mission_chain(apps, schema_editor):
    MediaFile = apps.get_model("media_file", "MediaFile")
    FlightRecord = apps.get_model("flight_record", "FlightRecord")
    Mission = apps.get_model("mission", "Mission")

    MediaFile.objects.all().delete()
    FlightRecord.objects.all().delete()
    Mission.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0011_user_is_platform_admin"),
        ("flight_record", "0005_alter_flightrecord_flight_no_and_more"),
        ("media_file", "0004_alter_mediafile_tenant"),
        ("mission", "0003_alter_mission_tenant"),
    ]

    operations = [
        migrations.RunPython(purge_legacy_mission_chain, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="mission",
            name="pilot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="missions",
                to="access.tenantmember",
                verbose_name="飞手成员",
            ),
        ),
    ]
