# Generated by Django 5.1.6 on 2026-04-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission", "0005_refactor_mission_for_dji_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="mission",
            name="device_sn",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="设备序列号（冗余）",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
    ]
