# Generated by Django 5.1.6 on 2026-05-27 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dji_bff", "0006_djicloudplatform_and_more"),
        ("mission", "0008_mission_execution_window"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="dji_platform",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missions",
                to="dji_bff.djicloudplatform",
                verbose_name="DJI 平台",
            ),
        ),
    ]
