# Generated by Django 5.1.6 on 2026-06-04 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam_v2", "0003_account_profile_contacts_and_qualifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="V2Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "disabled"), (1, "active")], default=1
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
                ("is_super_admin", models.BooleanField(default=False)),
                ("assignable_by_department_admin", models.BooleanField(default=False)),
                (
                    "data_scope",
                    models.CharField(
                        choices=[
                            ("ALL", "全平台数据"),
                            ("DEPT_AND_CHILDREN", "本部门及下级"),
                            ("DEPT_ONLY", "仅本部门"),
                            ("SELF", "本人数据"),
                            ("CUSTOM_DEPARTMENTS", "指定部门集合"),
                        ],
                        default="SELF",
                        max_length=32,
                    ),
                ),
                ("sort", models.IntegerField(default=100)),
                ("remark", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "v2_roles",
                "ordering": ["sort", "id"],
            },
        ),
        migrations.AlterField(
            model_name="v2accountroleassignment",
            name="role_code",
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name="V2Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=128, unique=True)),
                (
                    "menu_type",
                    models.CharField(
                        choices=[
                            ("DIRECTORY", "目录"),
                            ("MENU", "菜单"),
                            ("BUTTON", "按钮"),
                        ],
                        max_length=16,
                    ),
                ),
                ("path", models.CharField(blank=True, default="", max_length=255)),
                ("component", models.CharField(blank=True, default="", max_length=255)),
                ("icon", models.CharField(blank=True, default="", max_length=64)),
                ("sort", models.IntegerField(default=100)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "disabled"), (1, "active")], default=1
                    ),
                ),
                ("is_system", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="iam_v2.v2menu",
                    ),
                ),
            ],
            options={
                "db_table": "v2_menus",
                "ordering": ["sort", "id"],
            },
        ),
        migrations.CreateModel(
            name="V2Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("domain", models.CharField(max_length=64)),
                ("resource", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=64)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "disabled"), (1, "active")], default=1
                    ),
                ),
                ("is_system", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "v2_permissions",
                "ordering": ["domain", "resource", "action", "id"],
                "indexes": [
                    models.Index(
                        fields=["domain", "resource", "status"],
                        name="idx_v2_perm_domain_resource",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="V2MenuPermissionBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_bindings",
                        to="iam_v2.v2menu",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_bindings",
                        to="iam_v2.v2permission",
                    ),
                ),
            ],
            options={
                "db_table": "v2_menu_permission_bindings",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="V2RoleCustomDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_scope_roles",
                        to="iam_v2.department",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_departments",
                        to="iam_v2.v2role",
                    ),
                ),
            ],
            options={
                "db_table": "v2_role_custom_departments",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="V2RoleMenuGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_grants",
                        to="iam_v2.v2menu",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_grants",
                        to="iam_v2.v2role",
                    ),
                ),
            ],
            options={
                "db_table": "v2_role_menu_grants",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="V2RolePermissionGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("DIRECT", "直接授权"), ("MENU", "菜单授权")],
                        default="DIRECT",
                        max_length=16,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_grants",
                        to="iam_v2.v2permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_grants",
                        to="iam_v2.v2role",
                    ),
                ),
            ],
            options={
                "db_table": "v2_role_permission_grants",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="v2menu",
            index=models.Index(
                fields=["parent", "sort"], name="idx_v2_menu_parent_sort"
            ),
        ),
        migrations.AddIndex(
            model_name="v2menu",
            index=models.Index(
                fields=["menu_type", "status"], name="idx_v2_menu_type_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="v2menupermissionbinding",
            constraint=models.UniqueConstraint(
                fields=("menu", "permission"), name="uniq_v2_menu_permission"
            ),
        ),
        migrations.AddConstraint(
            model_name="v2rolecustomdepartment",
            constraint=models.UniqueConstraint(
                fields=("role", "department"), name="uniq_v2_role_custom_department"
            ),
        ),
        migrations.AddConstraint(
            model_name="v2rolemenugrant",
            constraint=models.UniqueConstraint(
                fields=("role", "menu"), name="uniq_v2_role_menu"
            ),
        ),
        migrations.AddConstraint(
            model_name="v2rolepermissiongrant",
            constraint=models.UniqueConstraint(
                fields=("role", "permission", "source"),
                name="uniq_v2_role_permission_source",
            ),
        ),
    ]
