# Generated by Django 5.1.6 on 2026-03-08 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flight_record", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "照片"), (2, "视频")], verbose_name="媒体类型"
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                ("file_url", models.CharField(max_length=500, verbose_name="文件URL")),
                (
                    "thumbnail_url",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="缩略图URL"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="文件大小（字节）"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=12,
                        null=True,
                        verbose_name="拍摄位置-纬度",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=12,
                        null=True,
                        verbose_name="拍摄位置-经度",
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="拍摄时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "flight_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_files",
                        to="flight_record.flightrecord",
                        verbose_name="关联飞行记录",
                    ),
                ),
            ],
            options={
                "db_table": "media_files",
                "ordering": ["-id"],
                "permissions": [("view_media_file", "可查看媒体文件")],
                "default_permissions": (),
            },
        ),
    ]
