# Generated by Django 5.1.6 on 2026-04-03 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_file", "0004_alter_mediafile_tenant"),
        ("mission", "0006_mission_deleted_at_mission_device_sn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="device_sn",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="设备序列号（冗余）",
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="mission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media_files",
                to="mission.mission",
                verbose_name="关联任务",
            ),
        ),
    ]
