# Generated by Django 5.1.6 on 2026-03-02 02:27

import apps.access.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'disabled'), (1, 'active')], default=1)),
            ],
            options={
                'db_table': 'staff_types',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'disabled'), (1, 'active')], default=1)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, db_table='auth_users_groups', help_text='业务上禁止用户直接绑定 Group。', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, db_table='auth_users_user_permissions', help_text='业务上禁止用户直接绑定权限点。', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_users',
                'permissions': [('view_user', '可查看账号'), ('manage_user_accounts', '可管理账号与人员档案')],
                'default_permissions': (),
            },
            managers=[
                ('objects', apps.access.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128)),
                ('target_type', models.CharField(max_length=128)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_audit_logs',
                'ordering': ['-created_at', '-id'],
                'permissions': [('view_auth_audit_logs', '可查看授权审计日志')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_no', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('employment_status', models.PositiveSmallIntegerField(choices=[(0, 'inactive'), (1, 'active')], default=1)),
                ('org_id', models.BigIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
                ('staff_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_profiles', to='access.stafftype')),
            ],
            options={
                'db_table': 'staff_profiles',
                'permissions': [('view_staffprofile', '可查看人员档案')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GroupPermissionScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(choices=[('ALL', 'ALL'), ('OWN', 'OWN'), ('ASSIGNED', 'ASSIGNED')], max_length=16)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'disabled'), (1, 'active')], default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_scopes', to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_scopes', to='auth.permission')),
            ],
            options={
                'db_table': 'auth_group_permission_scopes',
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('group', 'permission'), name='uniq_group_permission_scope')],
            },
        ),
        migrations.CreateModel(
            name='StaffTypeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'disabled'), (1, 'active')], default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_type_links', to='auth.group')),
                ('staff_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='access.stafftype')),
            ],
            options={
                'db_table': 'staff_type_groups',
                'permissions': [('manage_auth_groups', '可管理能力组与权限'), ('manage_auth_scopes', '可管理权限范围策略'), ('manage_staff_type_groups', '可管理身份类型能力组映射')],
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('staff_type', 'group'), name='uniq_staff_type_group')],
            },
        ),
    ]
