# Generated by Django 5.1.6 on 2026-03-02 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftype',
            name='is_registrable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RegistrationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_no', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('requested_staff_type_code', models.CharField(max_length=64)),
                ('requested_org_id', models.BigIntegerField(blank=True, null=True)),
                ('application_note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'PENDING_REVIEW'), ('APPROVED_ACCOUNT_CREATED', 'APPROVED_ACCOUNT_CREATED'), ('REJECTED', 'REJECTED')], default='PENDING_REVIEW', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.CharField(blank=True, max_length=255)),
                ('created_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_registration_applications', to='access.staffprofile')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_registration_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registration_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registration_applications',
                'ordering': ['-created_at', '-id'],
                'permissions': [('view_registration_application', '可查看注册申请'), ('manage_registration_application', '可审核注册申请')],
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING_REVIEW')), fields=('phone',), name='uniq_pending_registration_phone'), models.UniqueConstraint(condition=models.Q(('status', 'PENDING_REVIEW')), fields=('email',), name='uniq_pending_registration_email')],
            },
        ),
    ]
