# Generated by Django 5.1.6 on 2026-03-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="租户编码"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="租户名称")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "disabled"), (1, "enabled")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "plan",
                    models.CharField(blank=True, max_length=64, verbose_name="套餐"),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=500, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "租户",
                "verbose_name_plural": "租户",
                "db_table": "tenants",
                "permissions": [
                    ("view_tenant", "可查看租户"),
                    ("manage_tenant", "可管理租户"),
                ],
                "default_permissions": (),
            },
        ),
    ]
