# Generated by Django 5.1.6 on 2026-03-12 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0002_add_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="角色编码"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="角色名称")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="角色描述"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "disabled"), (1, "active")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "平台固定角色",
                "verbose_name_plural": "平台固定角色",
                "db_table": "system_roles",
                "permissions": [
                    ("view_system_role", "可查看固定角色"),
                    ("manage_system_role", "可管理固定角色"),
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="TenantMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "display_name",
                    models.CharField(max_length=128, verbose_name="显示名称"),
                ),
                (
                    "staff_no",
                    models.CharField(blank=True, max_length=64, verbose_name="工号"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, verbose_name="手机"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "pending"), (1, "active"), (2, "disabled")],
                        default=0,
                        verbose_name="状态",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="加入时间"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="access.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "租户成员",
                "verbose_name_plural": "租户成员",
                "db_table": "tenant_members",
                "permissions": [
                    ("view_tenant_member", "可查看租户成员"),
                    ("manage_tenant_member", "可管理租户成员"),
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="TenantMemberRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "disabled"), (1, "active")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "system_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_bindings",
                        to="access.systemrole",
                    ),
                ),
                (
                    "tenant_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_bindings",
                        to="access.tenantmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "成员角色绑定",
                "verbose_name_plural": "成员角色绑定",
                "db_table": "tenant_member_roles",
                "permissions": [("assign_tenant_member_role", "可分配成员角色")],
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="tenantmember",
            constraint=models.UniqueConstraint(
                fields=("tenant", "user"), name="uniq_tenant_user_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantmemberrole",
            constraint=models.UniqueConstraint(
                fields=("tenant_member", "system_role"), name="uniq_member_role"
            ),
        ),
    ]
