# Generated by Django 5.1.6 on 2026-03-12 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0003_add_tenant_member_system_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="access.tenant",
                verbose_name="租户",
            ),
        ),
    ]
