# Generated by Django 5.1.6 on 2026-03-13 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0005_add_invitation_token_to_tenant_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemRoleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "disabled"), (1, "active")],
                        default=1,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_role_links",
                        to="auth.group",
                    ),
                ),
                (
                    "system_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_links",
                        to="access.systemrole",
                    ),
                ),
            ],
            options={
                "verbose_name": "固定角色能力组映射",
                "verbose_name_plural": "固定角色能力组映射",
                "db_table": "system_role_groups",
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="systemrolegroup",
            constraint=models.UniqueConstraint(
                fields=("system_role", "group"),
                name="uniq_system_role_group",
            ),
        ),
    ]
