# Generated by Django 5.1.6 on 2026-03-13 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0006_add_system_role_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffprofile",
            name="staff_type",
        ),
        migrations.AlterModelOptions(
            name="grouppermissionscope",
            options={
                "default_permissions": (),
                "permissions": [
                    ("manage_auth_groups", "可管理能力组与权限"),
                    ("manage_auth_scopes", "可管理权限范围策略"),
                ],
                "verbose_name": "能力组权限范围",
                "verbose_name_plural": "能力组权限范围",
            },
        ),
        migrations.CreateModel(
            name="TenantMemberPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64, verbose_name="岗位编码")),
                ("name", models.CharField(max_length=128, verbose_name="岗位名称")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="岗位描述"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "disabled"), (1, "active")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "tenant_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="access.tenantmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "租户成员岗位",
                "verbose_name_plural": "租户成员岗位",
                "db_table": "tenant_member_positions",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="TenantMemberQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64, verbose_name="资质编码")),
                ("name", models.CharField(max_length=128, verbose_name="资质名称")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="资质描述"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "disabled"), (1, "active")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="有效期至"),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展信息"),
                ),
                (
                    "tenant_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="access.tenantmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "租户成员资质",
                "verbose_name_plural": "租户成员资质",
                "db_table": "tenant_member_qualifications",
                "default_permissions": (),
            },
        ),
        migrations.DeleteModel(
            name="StaffType",
        ),
        migrations.DeleteModel(
            name="StaffTypeGroup",
        ),
        migrations.AddConstraint(
            model_name="tenantmemberposition",
            constraint=models.UniqueConstraint(
                fields=("tenant_member", "code"),
                name="uniq_tenant_member_position_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantmemberqualification",
            constraint=models.UniqueConstraint(
                fields=("tenant_member", "code"),
                name="uniq_tenant_member_qualification_code",
            ),
        ),
    ]
