# Generated by Django 5.1.6 on 2026-03-14 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0007_remove_stafftypegroup_staff_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="GroupPermissionScope",
        ),
        migrations.DeleteModel(
            name="SystemRoleGroup",
        ),
        migrations.DeleteModel(
            name="TenantMemberPosition",
        ),
        migrations.DeleteModel(
            name="TenantMemberQualification",
        ),
        migrations.DeleteModel(
            name="TenantMemberRole",
        ),
        migrations.DeleteModel(
            name="SystemRole",
        ),
        migrations.RemoveField(
            model_name="tenantmember",
            name="email",
        ),
        migrations.RemoveField(
            model_name="tenantmember",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="tenantmember",
            name="staff_no",
        ),
        migrations.AddField(
            model_name="tenantmember",
            name="member_no",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="工号"),
        ),
        migrations.AddField(
            model_name="tenantmember",
            name="invited_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="邀请时间"),
        ),
        migrations.AddField(
            model_name="tenantmember",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="邀请过期时间"),
        ),
        migrations.AddField(
            model_name="tenantmember",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="响应时间"),
        ),
        migrations.AddField(
            model_name="tenantmember",
            name="invited_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_tenant_invitations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="邀请人",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "disabled"), (1, "active")],
                default=1,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="tenantmember",
            name="display_name",
            field=models.CharField(blank=True, max_length=128, verbose_name="显示名称"),
        ),
        migrations.AlterField(
            model_name="tenantmember",
            name="invitation_token",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="邀请令牌"),
        ),
        migrations.AlterField(
            model_name="tenantmember",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "invited"),
                    (1, "active"),
                    (2, "rejected"),
                    (3, "expired"),
                    (4, "revoked"),
                    (5, "disabled"),
                ],
                default=0,
                verbose_name="状态",
            ),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64, unique=True, verbose_name="角色编码")),
                ("name", models.CharField(max_length=128, verbose_name="角色名称")),
                ("description", models.CharField(blank=True, max_length=500, verbose_name="角色描述")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "disabled"), (1, "active")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "平台角色",
                "verbose_name_plural": "平台角色",
                "db_table": "roles",
                "permissions": [
                    ("view_role", "可查看平台角色"),
                    ("manage_role", "可管理平台角色"),
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=128, unique=True, verbose_name="权限编码")),
                ("name", models.CharField(max_length=128, verbose_name="权限名称")),
                ("module", models.CharField(max_length=64, verbose_name="模块")),
                ("resource_code", models.CharField(blank=True, max_length=64, verbose_name="资源编码")),
                ("description", models.CharField(blank=True, max_length=500, verbose_name="描述")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "disabled"), (1, "active")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "平台权限",
                "verbose_name_plural": "平台权限",
                "db_table": "permissions",
                "permissions": [
                    ("view_permission_catalog", "可查看权限目录"),
                    ("manage_permission_catalog", "可管理权限目录"),
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="QualificationType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64, unique=True, verbose_name="资质编码")),
                ("name", models.CharField(max_length=128, verbose_name="资质名称")),
                ("description", models.CharField(blank=True, max_length=500, verbose_name="资质描述")),
                ("requires_validity", models.BooleanField(default=False, verbose_name="是否要求有效期")),
                ("payload_schema_json", models.JSONField(blank=True, null=True, verbose_name="扩展字段 schema")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "disabled"), (1, "active")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "资质类型",
                "verbose_name_plural": "资质类型",
                "db_table": "qualification_types",
                "permissions": [
                    ("view_qualification_type", "可查看资质类型"),
                    ("manage_qualification_type", "可管理资质类型"),
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="RolePermissionGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scope_type", models.CharField(choices=[("ALL", "ALL"), ("OWN", "OWN"), ("ASSIGNED", "ASSIGNED")], default="ALL", max_length=16)),
                (
                    "permission",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="role_grants", to="access.permission"),
                ),
                (
                    "role",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="permission_grants", to="access.role"),
                ),
            ],
            options={
                "verbose_name": "角色权限映射",
                "verbose_name_plural": "角色权限映射",
                "db_table": "role_permission_grants",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="TenantMemberQualification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("certificate_no", models.CharField(blank=True, max_length=128, verbose_name="证书编号")),
                ("level", models.CharField(blank=True, max_length=64, verbose_name="等级")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "active"), (2, "invalid"), (3, "revoked")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                ("issued_at", models.DateField(blank=True, null=True, verbose_name="发证日期")),
                ("valid_from", models.DateField(blank=True, null=True, verbose_name="有效开始日期")),
                ("valid_until", models.DateField(blank=True, null=True, verbose_name="有效截止日期")),
                ("issuer", models.CharField(blank=True, max_length=128, verbose_name="发证机构")),
                ("payload_json", models.JSONField(blank=True, default=dict, verbose_name="扩展信息")),
                (
                    "qualification_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="member_records", to="access.qualificationtype"),
                ),
                (
                    "tenant_member",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="qualifications", to="access.tenantmember"),
                ),
            ],
            options={
                "verbose_name": "租户成员资质",
                "verbose_name_plural": "租户成员资质",
                "db_table": "tenant_member_qualifications",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="TenantMemberRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "revoked"), (1, "granted")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True, verbose_name="分配时间")),
                (
                    "assigned_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tenant_member_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分配人",
                    ),
                ),
                (
                    "system_role",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="member_bindings", to="access.role"),
                ),
                (
                    "tenant_member",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="role_bindings", to="access.tenantmember"),
                ),
            ],
            options={
                "verbose_name": "成员角色绑定",
                "verbose_name_plural": "成员角色绑定",
                "db_table": "tenant_member_roles",
                "permissions": [("assign_tenant_member_role", "可分配成员角色")],
                "default_permissions": (),
            },
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["module", "status"], name="idx_permission_module_status"),
        ),
        migrations.AddConstraint(
            model_name="tenantmember",
            constraint=models.UniqueConstraint(
                condition=Q(member_no__isnull=False) & ~Q(member_no=""),
                fields=("tenant", "member_no"),
                name="uniq_tenant_member_no",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantmember",
            constraint=models.UniqueConstraint(
                condition=Q(invitation_token__isnull=False) & ~Q(invitation_token=""),
                fields=("invitation_token",),
                name="uniq_tenant_member_invitation_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolepermissiongrant",
            constraint=models.UniqueConstraint(fields=("role", "permission"), name="uniq_role_permission_grant"),
        ),
        migrations.AddIndex(
            model_name="tenantmemberqualification",
            index=models.Index(fields=["tenant_member", "qualification_type"], name="idx_tm_qualification_type"),
        ),
        migrations.AddIndex(
            model_name="tenantmemberqualification",
            index=models.Index(fields=["tenant_member", "status"], name="idx_tm_qualification_status"),
        ),
        migrations.AddConstraint(
            model_name="tenantmemberqualification",
            constraint=models.CheckConstraint(
                condition=Q(valid_from__isnull=True)
                | Q(valid_until__isnull=True)
                | Q(valid_from__lte=models.F("valid_until")),
                name="chk_tm_qualification_valid_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantmemberrole",
            constraint=models.UniqueConstraint(fields=("tenant_member", "system_role"), name="uniq_member_role"),
        ),
    ]
