# Generated by Django 5.1.6 on 2026-03-15 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0009_purge_legacy_business_rows_before_tenant_hardening"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffprofile",
            name="staff_no",
        ),
    ]
