# Generated by Django 5.1.6 on 2026-03-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0010_remove_staffprofile_staff_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_platform_admin",
            field=models.BooleanField(default=False),
        ),
    ]
