# Generated by Django 5.1.6 on 2026-03-18 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0011_user_is_platform_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_type",
                    models.CharField(
                        choices=[("BUSINESS", "BUSINESS"), ("PLATFORM", "PLATFORM")],
                        max_length=16,
                    ),
                ),
                ("access_token_hash", models.CharField(max_length=64, unique=True)),
                ("refresh_token_hash", models.CharField(max_length=64, unique=True)),
                ("access_token_expires_at", models.DateTimeField()),
                ("refresh_token_expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "认证会话",
                "verbose_name_plural": "认证会话",
                "db_table": "auth_sessions",
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["user", "revoked_at"],
                        name="idx_auth_session_user_revoked",
                    ),
                    models.Index(
                        fields=["access_token_expires_at"],
                        name="idx_auth_session_access_exp",
                    ),
                    models.Index(
                        fields=["refresh_token_expires_at"],
                        name="idx_auth_session_refresh_exp",
                    ),
                ],
            },
        ),
    ]
