# Generated by refactor: move audit model ownership without rebuilding v2_audit_logs.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("iam_v2", "0001_initial"),
        ("resource_v2", "0004_dronetelemetrysnapshot_mqttconnectionhealth_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="V2AuditLog",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("action", models.CharField(max_length=128)),
                        ("resource_type", models.CharField(blank=True, max_length=16)),
                        ("resource_object_id", models.CharField(blank=True, max_length=64)),
                        ("target_type", models.CharField(max_length=128)),
                        ("target_id", models.CharField(blank=True, max_length=64)),
                        ("before_data", models.JSONField(blank=True, null=True)),
                        ("after_data", models.JSONField(blank=True, null=True)),
                        ("ip", models.GenericIPAddressField(blank=True, null=True)),
                        ("request_id", models.CharField(blank=True, max_length=64)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "actor_department",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="actor_v2_audit_logs",
                                to="iam_v2.department",
                            ),
                        ),
                        (
                            "actor_user",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="v2_audit_logs",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "resource_owner_department",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="resource_owner_v2_audit_logs",
                                to="iam_v2.department",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "v2_audit_logs",
                        "ordering": ["-created_at", "-id"],
                        "indexes": [
                            models.Index(fields=["actor_department", "created_at"], name="idx_v2_audit_actor_dept"),
                            models.Index(fields=["resource_type", "resource_object_id"], name="idx_v2_audit_resource"),
                        ],
                    },
                ),
            ],
        ),
    ]
